apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finalproject-release
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/sela-tracks/1101/nadav/my-final-project
    targetRevision: HEAD
    path: ./Expense-tracker-helm  # Path within your repo to the helm chart.
    sourceType: Helm
    helm:
      parameters:
        - name: image.repository  # Assuming your Helm values use this key
          value: nadavivry69/flask_nadav
        - name: image.tag  # Assuming your Helm values use this key
          value: latest
        - name: image.pullPolicy  # Ensure your Helm chart supports this parameter
          value: Always
    # Use the following section to specify a secret containing your GitLab PAT
    chartSource:
      repoURL: https://gitlab.com/sela-tracks/1101/nadav/my-final-project
      targetRevision: HEAD
      path: ./Expense-tracker-helm  # Path within your repo to the Helm chart
      repoURLSecret:
        name: argocd-gitlab-pat  # Name of the secret containing the PAT
        key: token  # Key within the secret that contains the PAT
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
