apiVersion: v1
kind: Pod
metadata:
  name: docker-image-build
spec:
  containers:
    - name: ez-docker-helm-build
      image: ezezeasy/ez-docker-helm-build:1.41
      imagePullPolicy: Always
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"  # Adjust memory limit as needed

    - name: python-test
      image: python:3.8-slim
      command: ["sleep"]
      args: ["infinity"]
      imagePullPolicy: Always
      securityContext:
        privileged: false
      resources:
        limits:
          cpu: "0.5"
          memory: "256Mi"  # Adjust memory limit as needed

    - name: docker-compose
      image: docker/compose:latest
      command: ["sleep"]
      args: ["infinity"]
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"  # Adjust memory limit as needed

  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
