version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/expense_tracker
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  test: 
    build: 
      context: .
      dockerfile: Dockerfile.test
    environment:
      - TEST_MONGODB_URI=mongodb://mongo:27017/expense_tracker
    depends_on:
      - mongo

volumes:
  mongo_data:

